name: fredericiana
description: open source, the web, and german-american oddities
url: http://fredericiana.com

pygments: true
markdown: rdiscount
permalink: /:year/:month/:day/:title/
paginate: 10

analytics: UA-291336-2